name: Trigger Supabase Edge Function Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:        # Allows manual trigger

jobs:
  call-supabase-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -X POST "$SUPABASE_FUNCTION_URL" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
          -d "{}"
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_FUNCTION_URL: ${{ secrets.SUPABASE_FUNCTION_URL }}
